/**
 * Hub Studio App v8 (Infinity) - Live App Editor
 */


const HubStudioApp = {
    init(containerId) {
        this.container = document.getElementById(containerId);
        this.render();
        return () => {};
    },

    render() {
        this.container.innerHTML = `
            <div class="hub-studio">
                <div class="studio-sidebar">
                    <h3>App Wizard</h3>
                    <div class="wizard-step">
                        <label>App ID</label>
                        <input type="text" id="studio-id" placeholder="my-app">
                    </div>
                    <div class="wizard-step">
                        <label>App Name</label>
                        <input type="text" id="studio-name" placeholder="My New App">
                    </div>
                    <div class="wizard-step">
                        <label>Icon (FA Class)</label>
                        <input type="text" id="studio-icon" placeholder="fa-rocket">
                    </div>
                    <button class="primary" onclick="HubStudioApp.generateTemplate()">Generate Template</button>
                    <button class="secondary" onclick="HubStudioApp.injectApp()">Inject Into System</button>
                </div>
                <div class="studio-main">
                    <div class="editor-header">
                        <span>main.js</span>
                    </div>
                    <textarea id="studio-editor" spellcheck="false"></textarea>
                </div>
            </div>
            <style>
                .hub-studio { display: flex; height: 100%; background: #252526; color: #cccccc; font-family: 'Segoe UI', sans-serif; }
                .studio-sidebar { width: 250px; border-right: 1px solid #3c3c3c; padding: 20px; display: flex; flex-direction: column; gap: 15px; background: #333333; }
                .studio-sidebar h3 { font-size: 0.9rem; text-transform: uppercase; letter-spacing: 1px; color: #888; margin-bottom: 10px; }
                .wizard-step { display: flex; flex-direction: column; gap: 5px; }
                .wizard-step label { font-size: 0.8rem; opacity: 0.7; }
                .wizard-step input { background: #3c3c3c; border: 1px solid #555; color: white; padding: 8px; border-radius: 4px; outline: none; }
                .studio-sidebar button { padding: 10px; border: none; border-radius: 4px; cursor: pointer; font-weight: bold; }
                .studio-sidebar button.primary { background: #0078d4; color: white; margin-top: 10px; }
                .studio-sidebar button.secondary { background: #444; color: white; }

                .studio-main { flex-grow: 1; display: flex; flex-direction: column; }
                .editor-header { background: #2d2d2d; padding: 10px 20px; font-size: 0.8rem; border-bottom: 1px solid #3c3c3c; }
                #studio-editor { flex-grow: 1; background: #1e1e1e; color: #d4d4d4; border: none; padding: 20px; font-family: 'Consolas', 'Courier New', monospace; font-size: 14px; outline: none; resize: none; line-height: 1.5; }
            </style>
        `;
    },

    generateTemplate() {
        const id = document.getElementById('studio-id').value || 'my-app';
        const name = document.getElementById('studio-name').value || 'My App';
        const className = name.replace(/\s+/g, '') + 'App';

        const template = `/**
 * ${name} - Hub Studio Generated
 */

const ${className} = {
    init(containerId, params = {}) {
        const container = document.getElementById(containerId);
        container.innerHTML = \`
            <div style="padding: 20px; text-align: center;">
                <h2>Welcome to ${name}</h2>
                <p>Generated by Hub Studio v8.0</p>
                <button id="btn-\${containerId}" style="padding: 10px 20px; background: #0078d4; color: white; border: none; border-radius: 4px; cursor: pointer;">
                    Click Me!
                </button>
            </div>
        \`;

        const btn = document.getElementById(\`btn-\${containerId}\`);
        btn.onclick = () => {
            Utils.showToast("Hello from ${name}!", "success");
            Utils.notify("${name}", "Someone clicked the button inside your new app!", "fa-rocket");
        };

        return () => {
            console.log("${name} cleaning up...");
        };
    }
};
`;
        document.getElementById('studio-editor').value = template;
    },

    async injectApp() {
        const id = document.getElementById('studio-id').value;
        const name = document.getElementById('studio-name').value;
        const icon = document.getElementById('studio-icon').value || 'fa-rocket';
        const code = document.getElementById('studio-editor').value;

        if (!id || !code) {
            Utils.showToast("App ID and Code are required!", "danger");
            return;
        }

        try {
            // 1. Evaluate the code globally
            eval(code);

            // 2. Add to Virtual File System
            await VFS.writeFile(`/system/apps/${id}.js`, code, 'text/javascript');

            // 3. Register in Sidebar
            const ext = { id, name, icon, internal: true };
            ExtensionManager.addToSidebar(ext);

            Utils.showToast(`App "${name}" injected successfully!`, "success");
            Utils.notify("Infinity Hub: System Expansion", `A new application "${name}" has been hot-swapped into the system.`, "fa-bolt", "success");
        } catch (e) {
            Utils.showToast("Injection failed: " + e.message, "danger");
        }
    }
};
